# App Build Configuration
# This file contains build configuration properties for the Android app
# Load this file in android/app/build.gradle.kts

# Version Information
app.versionCode=22
app.versionName=1.0.2
app.versionNameSuffix=+2
# Build Configuration
app.buildMode=release
app.minSdk=28
app.targetSdk=33
app.compileSdk=36

# application ID
app.applicationId=com.zili_coffee.seller

# Signing Configuration (optional - for release builds)
# app.storeFile=path/to/keystore.jks
# app.storePassword=your_store_password
# app.keyAlias=your_key_alias
# app.keyPassword=your_key_password

