// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

import 'app/app_flavor_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static String get appName {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return "${FlavorConfig.instance.env.appName}";
      case TargetPlatform.iOS:
        return "Zili-Coffee-Seller";
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPzOHIUnyWJIXJqPEnyXWiVTFOHCa_Q3o',
    appId: '1:180826362406:android:be17bf1385bf187957cce7',
    messagingSenderId: '180826362406',
    projectId: 'zili-ecom',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRrcjK_p5nkp-Zl4yk0_8BZe3UmYbcV54',
    appId: '1:180826362406:ios:e0e45643fd2f8a0757cce7',
    messagingSenderId: '180826362406',
    projectId: 'zili-ecom',
    storageBucket: 'zili-ecom.firebasestorage.app',
    iosBundleId: 'com.zili.seller.stg',
  );
}
